version: "3"

services:
    apache:
        build: ./apache
        container_name: apache
        tty: true
        networks:
            net-192.168.123.0:
                ipv4_address: 192.168.123.10
        volumes:
                - ./apache/shared:/root/shared
                - ./apache/src:/root/src
        ports:
          - '80:8080'
                  
    attacker:
        build: ./attacker
        container_name: attacker
        tty: true
        networks:
            net-192.168.123.0:
                ipv4_address: 192.168.123.20
        volumes:
                - ./attacker/shared:/root/shared

networks:
    net-192.168.123.0:
        name: net-192.168.123.0
        ipam:
            config:
                - subnet: 192.168.123.0/24

